# netlify.toml
[build]
  command = "npm install"
  publish = "." # Pastikan ini ke root directory

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 20

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/"
  status = 200
  force = true