# netlify.toml
[build]
  command = "npm install"
  publish = "." # UBAH INI ke root directory, atau biarkan kosong jika Netlify mengizinkan
                # Atau bisa juga pakai folder yang pasti kosong, misal "public" atau "temp"
                # Tapi "." adalah yang paling aman untuk proyek API murni tanpa frontend.

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/"
  status = 200
  force = true