# netlify.toml
[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions" # Pastikan ini sesuai dengan struktur folder Anda
  node_bundler = "esbuild"
  # Pastikan tidak ada konfigurasi 'timeout' yang salah di sini.
  # Jika Anda sebelumnya mencoba menambah timeout dan mendapatkan error, hapus baris itu.

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/"
  status = 200
  force = true